name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  security-events: write

concurrency:
  group: ${{github.head_ref || github.run_id}}
  cancel-in-progress: true

jobs:
  build:
    name: Build with maven
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn -B process-test-classes -DskipTests

  test:
    name: Run unit tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run unit tests
      run: mvn -B -Dmaven.test.failure.ignore=true test
    - name: Gather test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Report
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true

  analyze:
    name: Analyze with CodeQL
    needs: build
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360
    strategy:
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java-kotlin
    - name: Build
      run: mvn -B package -DskipTests
    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:java-kotlin"
