name: SBOM Generator

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: advanced-security/sbom-generator-action@0.0.1
        id: sbom
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: "SBOM"
          path: ${{ steps.sbom.outputs.fileName }}
